name: Ejemplo CI/CD

on: [push]

jobs:
  inicio:
    runs-on: windows-latest
    #Pasos
    steps:
      - name: mostrar texto
        run: echo "Hola mundo"
  build:
    runs-on: windows-latest
    needs: [inicio]
    steps:
      - name: mostrar texto
        run: echo "Adios"
  test:
    runs-on: windows-latest
    needs: [build]
    steps:
      - name: mostrar texto
        run: echo "TEST"
  deploy:
    runs-on: windows-latest
    needs: [test]
    steps:
      - name: mostrar texto
        run: echo "DEPLOY"
  